    class cop_car {
        side = "cop";
        vehicles[] = {
            // ALL
            { "C_Offroad_01_F", 5000, { "" }, {"life_coplevel", "SCALAR", 0 } },
            { "C_SUV_01_F", 20000, { "" }, {"life_coplevel", "SCALAR", 0 } },
            // CADET[0]
            { "Mrshounka_a3_308_gend", 1000, { "" }, {"life_coplevel", "EQUAL", 0 } },
            { "C_Hatchback_01_sport_F", 30000, { "" }, { "life_coplevel", "EQUAL", 0} },
            // PRIVATE[1]
            { "Mrshounka_a3_308_gend", 1000, { "" }, {"life_coplevel", "EQUAL", 1 } },
            // L_SGT[2]
            { "Mrshounka_a3_308_gend", 1000, { "" }, {"life_coplevel", "EQUAL", 2 } },
            { "Mrshounka_rs_2015_g", 1000, { "" }, {"life_coplevel", "EQUAL", 2 } },            
            { "B_MRAP_01_F", 30000, { "" }, { "life_coplevel", "EQUAL", 2 } },
            // SGT[3]
            { "Mrshounka_a3_308_gend", 1000, { "" }, {"life_coplevel", "EQUAL", 3 } },
            { "Mrshounka_rs_2015_g", 1000, { "" }, {"life_coplevel", "EQUAL", 3 } },            
            { "B_MRAP_01_hmg_F", 750000, { "" }, { "life_coplevel", "EQUAL", 3 } },
            // ST_SGT[4]
            { "Mrshounka_a3_308_gend", 1000, { "" }, {"life_coplevel", "EQUAL", 4 } },
            { "Mrshounka_rs_2015_g", 1000, { "" }, {"life_coplevel", "EQUAL", 4 } },
            // DETECTIVE[5]

            // STARSHINA[6]
            { "Mrshounka_a3_308_gend", 1000, { "" }, {"life_coplevel", "EQUAL", 6 } },
            { "Mrshounka_rs_2015_g", 1000, { "" }, {"life_coplevel", "EQUAL", 6 } },
            { "shounka_a3_gendsprinter", 1000, { "" }, {"life_coplevel", "EQUAL", 6 } },
            { "shounka_a3_508gend", 1000, { "" }, {"life_coplevel", "EQUAL", 6 } },
            { "shounka_a3_cliors_gend_civ", 1000, { "" }, {"life_coplevel", "EQUAL", 6 } },
            // PRAPOR[7]
            { "Mrshounka_a3_308_gend", 1000, { "" }, {"life_coplevel", "EQUAL", 7 } },
            { "Mrshounka_rs_2015_g", 1000, { "" }, {"life_coplevel", "EQUAL", 7 } },
            { "shounka_a3_gendsprinter", 1000, { "" }, {"life_coplevel", "EQUAL", 7 } },
            { "shounka_a3_508gend", 1000, { "" }, {"life_coplevel", "EQUAL", 7 } },
            { "shounka_a3_cliors_gend_civ", 1000, { "" }, {"life_coplevel", "EQUAL", 7 } },
            // ST_PRAPOR[8]
            { "Mrshounka_a3_308_gend", 1000, { "" }, {"life_coplevel", "EQUAL", 8 } },
            { "Mrshounka_rs_2015_g", 1000, { "" }, {"life_coplevel", "EQUAL", 8 } },
            { "shounka_a3_gendsprinter", 1000, { "" }, {"life_coplevel", "EQUAL", 8 } },
            { "shounka_a3_508gend", 1000, { "" }, {"life_coplevel", "EQUAL", 8 } },
            { "shounka_a3_cliors_gend_civ", 1000, { "" }, {"life_coplevel", "EQUAL", 8 } },
            // L_LEYT[9]
            { "Mrshounka_a3_308_gend", 1000, { "" }, {"life_coplevel", "EQUAL", 9 } },
            { "Mrshounka_rs_2015_g", 1000, { "" }, {"life_coplevel", "EQUAL", 9 } },
            { "shounka_a3_gendsprinter", 1000, { "" }, {"life_coplevel", "EQUAL", 9 } },
            { "shounka_a3_508gend", 1000, { "" }, {"life_coplevel", "EQUAL", 9 } },
            { "shounka_a3_cliors_gend_civ", 1000, { "" }, {"life_coplevel", "EQUAL", 9 } },
            { "Mrshounka_bmw_gend", 1000, { "" }, {"life_coplevel", "EQUAL", 9 } },
            { "Mrshounka_Volkswagen_Touareg_police_police", 1000, { "" }, {"life_coplevel", "EQUAL", 9 } },
            { "Mrshounka_ducati_police_p", 1000, { "" }, {"life_coplevel", "EQUAL", 9 } },
            { "Mrshounka_tahoe", 1000, { "" }, {"life_coplevel", "EQUAL", 9 } },
            // LEYT[10]
            { "Mrshounka_a3_308_gend", 1000, { "" }, {"life_coplevel", "EQUAL", 10 } },
            { "Mrshounka_rs_2015_g", 1000, { "" }, {"life_coplevel", "EQUAL", 10 } },
            { "shounka_a3_gendsprinter", 1000, { "" }, {"life_coplevel", "EQUAL", 10 } },
            { "shounka_a3_508gend", 1000, { "" }, {"life_coplevel", "EQUAL", 10 } },
            { "shounka_a3_cliors_gend_civ", 1000, { "" }, {"life_coplevel", "EQUAL", 10 } },
            { "Mrshounka_bmw_gend", 1000, { "" }, {"life_coplevel", "EQUAL", 10 } },
            { "Mrshounka_Volkswagen_Touareg_police_police", 1000, { "" }, {"life_coplevel", "EQUAL", 10 } },
            { "Mrshounka_ducati_police_p", 1000, { "" }, {"life_coplevel", "EQUAL", 10 } },
            { "Mrshounka_tahoe", 1000, { "" }, {"life_coplevel", "EQUAL", 10 } },
            // ST_LEYT[11]           
            { "Mrshounka_a3_308_gend", 1000, { "" }, {"life_coplevel", "EQUAL", 11 } },
            { "Mrshounka_rs_2015_g", 1000, { "" }, {"life_coplevel", "EQUAL", 11 } },
            { "shounka_a3_gendsprinter", 1000, { "" }, {"life_coplevel", "EQUAL", 11 } },
            { "shounka_a3_508gend", 1000, { "" }, {"life_coplevel", "EQUAL", 11 } },
            { "shounka_a3_cliors_gend_civ", 1000, { "" }, {"life_coplevel", "EQUAL", 11 } },
            { "Mrshounka_bmw_gend", 1000, { "" }, {"life_coplevel", "EQUAL", 11 } },
            { "Mrshounka_Volkswagen_Touareg_police_police", 1000, { "" }, {"life_coplevel", "EQUAL", 11 } },
            { "Mrshounka_ducati_police_p", 1000, { "" }, {"life_coplevel", "EQUAL", 11 } },
            { "Mrshounka_tahoe", 1000, { "" }, {"life_coplevel", "EQUAL", 11 } },
            // CAPTAIN[12]
            { "Mrshounka_a3_308_gend", 1000, { "" }, {"life_coplevel", "EQUAL", 12 } },
            { "Mrshounka_rs_2015_g", 1000, { "" }, {"life_coplevel", "EQUAL", 12 } },
            { "shounka_a3_gendsprinter", 1000, { "" }, {"life_coplevel", "EQUAL", 12 } },
            { "shounka_a3_508gend", 1000, { "" }, {"life_coplevel", "EQUAL", 12 } },
            { "shounka_a3_cliors_gend_civ", 1000, { "" }, {"life_coplevel", "EQUAL", 12 } },
            { "Mrshounka_bmw_gend", 1000, { "" }, {"life_coplevel", "EQUAL", 12 } },
            { "Mrshounka_Volkswagen_Touareg_police_police", 1000, { "" }, {"life_coplevel", "EQUAL", 12 } },
            { "Mrshounka_ducati_police_p", 1000, { "" }, {"life_coplevel", "EQUAL", 12 } },
            { "Mrshounka_tahoe", 1000, { "" }, {"life_coplevel", "EQUAL", 12 } },
            { "shounka_a3_audiq7_v2_gendarmerie", 1000, { "" }, {"life_coplevel", "EQUAL", 12 } },
            { "Mrshounka_cayman_z", 1000, { "" }, {"life_coplevel", "EQUAL", 12 } },
            // MAJOR[13]
            { "Mrshounka_a3_308_gend", 1000, { "" }, {"life_coplevel", "EQUAL", 13 } },
            { "Mrshounka_rs_2015_g", 1000, { "" }, {"life_coplevel", "EQUAL", 13 } },
            { "shounka_a3_gendsprinter", 1000, { "" }, {"life_coplevel", "EQUAL", 13 } },
            { "shounka_a3_508gend", 1000, { "" }, {"life_coplevel", "EQUAL", 13 } },
            { "shounka_a3_cliors_gend_civ", 1000, { "" }, {"life_coplevel", "EQUAL", 13 } },
            { "Mrshounka_bmw_gend", 1000, { "" }, {"life_coplevel", "EQUAL", 13 } },
            { "Mrshounka_Volkswagen_Touareg_police_police", 1000, { "" }, {"life_coplevel", "EQUAL", 13 } },
            { "Mrshounka_ducati_police_p", 1000, { "" }, {"life_coplevel", "EQUAL", 13 } },
            { "Mrshounka_tahoe", 1000, { "" }, {"life_coplevel", "EQUAL", 13 } },
            { "shounka_a3_audiq7_v2_gendarmerie", 1000, { "" }, {"life_coplevel", "EQUAL", 13 } },
            { "Mrshounka_cayman_z", 1000, { "" }, {"life_coplevel", "EQUAL", 13 } },
            //podpol[14]
            { "Mrshounka_a3_308_gend", 1000, { "" }, {"life_coplevel", "EQUAL", 14 } },
            { "Mrshounka_rs_2015_g", 1000, { "" }, {"life_coplevel", "EQUAL", 14 } },
            { "shounka_a3_gendsprinter", 1000, { "" }, {"life_coplevel", "EQUAL", 14 } },
            { "shounka_a3_508gend", 1000, { "" }, {"life_coplevel", "EQUAL", 14 } },
            { "shounka_a3_cliors_gend_civ", 1000, { "" }, {"life_coplevel", "EQUAL", 14 } },
            { "Mrshounka_bmw_gend", 1000, { "" }, {"life_coplevel", "EQUAL", 14 } },
            { "Mrshounka_Volkswagen_Touareg_police_police", 1000, { "" }, {"life_coplevel", "EQUAL", 14 } },
            { "Mrshounka_ducati_police_p", 1000, { "" }, {"life_coplevel", "EQUAL", 14 } },
            { "Mrshounka_tahoe", 1000, { "" }, {"life_coplevel", "EQUAL", 14 } },
            { "shounka_a3_audiq7_v2_gendarmerie", 1000, { "" }, {"life_coplevel", "EQUAL", 14 } },
            { "Mrshounka_cayman_z", 1000, { "" }, {"life_coplevel", "EQUAL", 14 } },
            //pol[15]
            { "Mrshounka_a3_308_gend", 1000, { "" }, {"life_coplevel", "EQUAL", 15 } },
            { "Mrshounka_rs_2015_g", 1000, { "" }, {"life_coplevel", "EQUAL", 15 } },
            { "shounka_a3_gendsprinter", 1000, { "" }, {"life_coplevel", "EQUAL", 15 } },
            { "shounka_a3_508gend", 1000, { "" }, {"life_coplevel", "EQUAL", 15 } },
            { "shounka_a3_cliors_gend_civ", 1000, { "" }, {"life_coplevel", "EQUAL", 15 } },
            { "Mrshounka_bmw_gend", 1000, { "" }, {"life_coplevel", "EQUAL", 15 } },
            { "Mrshounka_Volkswagen_Touareg_police_police", 1000, { "" }, {"life_coplevel", "EQUAL", 15 } },
            { "Mrshounka_ducati_police_p", 1000, { "" }, {"life_coplevel", "EQUAL", 15 } },
            { "Mrshounka_tahoe", 1000, { "" }, {"life_coplevel", "EQUAL", 15 } },
            { "shounka_a3_audiq7_v2_gendarmerie", 1000, { "" }, {"life_coplevel", "EQUAL", 15 } },
            { "Mrshounka_cayman_z", 1000, { "" }, {"life_coplevel", "EQUAL", 15 } },
            //chief[16]
            { "Mrshounka_a3_308_gend", 1000, { "" }, {"life_coplevel", "EQUAL", 16 } },
            { "Mrshounka_rs_2015_g", 1000, { "" }, {"life_coplevel", "EQUAL", 16 } },
            { "shounka_a3_gendsprinter", 1000, { "" }, {"life_coplevel", "EQUAL", 16 } },
            { "shounka_a3_508gend", 1000, { "" }, {"life_coplevel", "EQUAL", 16 } },
            { "shounka_a3_cliors_gend_civ", 1000, { "" }, {"life_coplevel", "EQUAL", 16 } },
            { "Mrshounka_bmw_gend", 1000, { "" }, {"life_coplevel", "EQUAL", 16 } },
            { "Mrshounka_Volkswagen_Touareg_police_police", 1000, { "" }, {"life_coplevel", "EQUAL", 16 } },
            { "Mrshounka_ducati_police_p", 1000, { "" }, {"life_coplevel", "EQUAL", 16 } },
            { "Mrshounka_tahoe", 1000, { "" }, {"life_coplevel", "EQUAL", 16 } },
            { "shounka_a3_audiq7_v2_gendarmerie", 1000, { "" }, {"life_coplevel", "EQUAL", 16 } },
            { "Mrshounka_cayman_z", 1000, { "" }, {"life_coplevel", "EQUAL", 16 } },
            { "Mrshounka_agera_gend_p", 1000, { "" }, {"life_coplevel", "EQUAL", 16 } },
            //*och_1[17], */
            { "Mrshounka_a3_308_gend", 1000, { "" }, {"life_coplevel", "EQUAL", 17 } },
            { "Mrshounka_rs_2015_g", 1000, { "" }, {"life_coplevel", "EQUAL", 17 } },
            { "shounka_a3_gendsprinter", 1000, { "" }, {"life_coplevel", "EQUAL", 17 } },
            { "shounka_a3_508gend", 1000, { "" }, {"life_coplevel", "EQUAL", 17 } },
            { "shounka_a3_cliors_gend_civ", 1000, { "" }, {"life_coplevel", "EQUAL", 17 } },
            { "Mrshounka_bmw_gend", 1000, { "" }, {"life_coplevel", "EQUAL", 17 } },
            { "Mrshounka_Volkswagen_Touareg_police_police", 1000, { "" }, {"life_coplevel", "EQUAL", 17 } },
            { "Mrshounka_ducati_police_p", 1000, { "" }, {"life_coplevel", "EQUAL", 17 } },
            { "Mrshounka_tahoe", 1000, { "" }, {"life_coplevel", "EQUAL", 17 } },
            { "shounka_a3_audiq7_v2_gendarmerie", 1000, { "" }, {"life_coplevel", "EQUAL", 17 } },
            { "Mrshounka_cayman_z", 1000, { "" }, {"life_coplevel", "EQUAL", 17 } },
            //och_2[18]
            { "Mrshounka_a3_308_gend", 1000, { "" }, {"life_coplevel", "EQUAL", 18 } },
            { "Mrshounka_rs_2015_g", 1000, { "" }, {"life_coplevel", "EQUAL", 18 } },
            { "shounka_a3_gendsprinter", 1000, { "" }, {"life_coplevel", "EQUAL", 18 } },
            { "shounka_a3_508gend", 1000, { "" }, {"life_coplevel", "EQUAL", 18 } },
            { "shounka_a3_cliors_gend_civ", 1000, { "" }, {"life_coplevel", "EQUAL", 18 } },
            { "Mrshounka_bmw_gend", 1000, { "" }, {"life_coplevel", "EQUAL", 18 } },
            { "Mrshounka_Volkswagen_Touareg_police_police", 1000, { "" }, {"life_coplevel", "EQUAL", 18 } },
            { "Mrshounka_ducati_police_p", 1000, { "" }, {"life_coplevel", "EQUAL", 18 } },
            { "Mrshounka_tahoe", 1000, { "" }, {"life_coplevel", "EQUAL", 18 } },
            { "shounka_a3_audiq7_v2_gendarmerie", 1000, { "" }, {"life_coplevel", "EQUAL", 18 } },
            { "Mrshounka_cayman_z", 1000, { "" }, {"life_coplevel", "EQUAL", 18 } },
            //och_3[19]
            { "Mrshounka_a3_308_gend", 1000, { "" }, {"life_coplevel", "EQUAL", 19 } },
            { "Mrshounka_rs_2015_g", 1000, { "" }, {"life_coplevel", "EQUAL", 19 } },
            { "shounka_a3_gendsprinter", 1000, { "" }, {"life_coplevel", "EQUAL", 19 } },
            { "shounka_a3_508gend", 1000, { "" }, {"life_coplevel", "EQUAL", 19 } },
            { "shounka_a3_cliors_gend_civ", 1000, { "" }, {"life_coplevel", "EQUAL", 19 } },
            { "Mrshounka_bmw_gend", 1000, { "" }, {"life_coplevel", "EQUAL", 19 } },
            { "Mrshounka_Volkswagen_Touareg_police_police", 1000, { "" }, {"life_coplevel", "EQUAL", 19 } },
            { "Mrshounka_ducati_police_p", 1000, { "" }, {"life_coplevel", "EQUAL", 19 } },
            { "Mrshounka_tahoe", 1000, { "" }, {"life_coplevel", "EQUAL", 19 } },
            { "shounka_a3_audiq7_v2_gendarmerie", 1000, { "" }, {"life_coplevel", "EQUAL", 19 } },
            { "Mrshounka_cayman_z", 1000, { "" }, {"life_coplevel", "EQUAL", 19 } },
            //rsb_1[20]
            { "Mrshounka_a3_308_gend", 1000, { "" }, {"life_coplevel", "EQUAL", 20 } },
            { "Mrshounka_rs_2015_g", 1000, { "" }, {"life_coplevel", "EQUAL", 20 } },
            { "shounka_a3_gendsprinter", 1000, { "" }, {"life_coplevel", "EQUAL", 20 } },
            { "shounka_a3_508gend", 1000, { "" }, {"life_coplevel", "EQUAL", 20 } },
            { "shounka_a3_cliors_gend_civ", 1000, { "" }, {"life_coplevel", "EQUAL", 20 } },
            { "Mrshounka_bmw_gend", 1000, { "" }, {"life_coplevel", "EQUAL", 20 } },
            { "Mrshounka_Volkswagen_Touareg_police_police", 1000, { "" }, {"life_coplevel", "EQUAL", 20 } },
            { "Mrshounka_ducati_police_p", 1000, { "" }, {"life_coplevel", "EQUAL", 20 } },
            { "Mrshounka_tahoe", 1000, { "" }, {"life_coplevel", "EQUAL", 20 } },
            { "shounka_a3_audiq7_v2_gendarmerie", 1000, { "" }, {"life_coplevel", "EQUAL", 20 } },
            { "Mrshounka_cayman_z", 1000, { "" }, {"life_coplevel", "EQUAL", 20 } },
            { "Mrshounka_agera_gend_p", 1000, { "" }, {"life_coplevel", "EQUAL", 20 } },
            //rsb_2[21]
            { "Mrshounka_a3_308_gend", 1000, { "" }, {"life_coplevel", "EQUAL", 21 } },
            { "Mrshounka_rs_2015_g", 1000, { "" }, {"life_coplevel", "EQUAL", 21 } },
            { "shounka_a3_gendsprinter", 1000, { "" }, {"life_coplevel", "EQUAL", 21 } },
            { "shounka_a3_508gend", 1000, { "" }, {"life_coplevel", "EQUAL", 21 } },
            { "shounka_a3_cliors_gend_civ", 1000, { "" }, {"life_coplevel", "EQUAL", 21 } },
            { "Mrshounka_bmw_gend", 1000, { "" }, {"life_coplevel", "EQUAL", 21 } },
            { "Mrshounka_Volkswagen_Touareg_police_police", 1000, { "" }, {"life_coplevel", "EQUAL", 21 } },
            { "Mrshounka_ducati_police_p", 1000, { "" }, {"life_coplevel", "EQUAL", 21 } },
            { "Mrshounka_tahoe", 1000, { "" }, {"life_coplevel", "EQUAL", 21 } },
            { "shounka_a3_audiq7_v2_gendarmerie", 1000, { "" }, {"life_coplevel", "EQUAL", 21 } },
            { "Mrshounka_cayman_z", 1000, { "" }, {"life_coplevel", "EQUAL", 21 } },
            { "Mrshounka_agera_gend_p", 1000, { "" }, {"life_coplevel", "EQUAL", 21 } },
            //rsb_3[22]
            { "Mrshounka_a3_308_gend", 1000, { "" }, {"life_coplevel", "EQUAL", 22 } },
            { "Mrshounka_rs_2015_g", 1000, { "" }, {"life_coplevel", "EQUAL", 22 } },
            { "shounka_a3_gendsprinter", 1000, { "" }, {"life_coplevel", "EQUAL", 22 } },
            { "shounka_a3_508gend", 1000, { "" }, {"life_coplevel", "EQUAL", 22 } },
            { "shounka_a3_cliors_gend_civ", 1000, { "" }, {"life_coplevel", "EQUAL", 22 } },
            { "Mrshounka_bmw_gend", 1000, { "" }, {"life_coplevel", "EQUAL", 22 } },
            { "Mrshounka_Volkswagen_Touareg_police_police", 1000, { "" }, {"life_coplevel", "EQUAL", 22 } },
            { "Mrshounka_ducati_police_p", 1000, { "" }, {"life_coplevel", "EQUAL", 22 } },
            { "Mrshounka_tahoe", 1000, { "" }, {"life_coplevel", "EQUAL", 22 } },
            { "shounka_a3_audiq7_v2_gendarmerie", 1000, { "" }, {"life_coplevel", "EQUAL", 22 } },
            { "Mrshounka_cayman_z", 1000, { "" }, {"life_coplevel", "EQUAL", 22 } },
            { "Mrshounka_agera_gend_p", 1000, { "" }, {"life_coplevel", "EQUAL", 22 } }
        };
    };
